model: {
  out_dim: 8,
  num_feature: 64,
}

env: {
  device: 'cuda',
  random_seed: 0
}

dataset: {
  label_csv_path: '/home/dw-dengwei/dataset/tissue/train.csv',
  image_root: '/home/dw-dengwei/dataset/tissue/train/'
}

exp: {
  train_batch_size: 256,
  valid_batch_size: 256,
  epoch_num: 100,
  learning_rate: 5e-4,
  weight_decay: 9e-2,
  l1_norm_weight: 0
}
