model: {
  out_dim: 8,
  num_feature: 8,
}

env: {
  device: 'cuda',
  random_seed: 0
}

dataset: {
  label_csv_path: '/home/dw-dengwei/dataset/tissue/train.csv',
  image_root: '/home/dw-dengwei/dataset/tissue/train/',
  augment_label_csv_path: '/home/dw-dengwei/dataset/tissue/aug_train.csv',
  augment_image_root: '/home/dw-dengwei/dataset/tissue/augment/'
}

exp: {
  do_augment: False,
  train_batch_size: 128,
  valid_batch_size: 128,
  epoch_num: 50,
  learning_rate: 0.025336627337952815,
  weight_decay: 0.0046684446208345,
  l1_norm_weight: 0
}
